### PR TITLE
improve formatting

### PR DESCRIPTION
**Pull request by matkoniecz**
remove formatting everything as a header

### CODE REVIEW

**Comment by matkoniecz** [comment]
Is it closed because formatting everything as header is intentional?

Or because this project is no longer active and no PRs of any kind will be accepted?

**Comment by dougmassay** [comment]
It's closed because this repo is no longer maintained, and because I generally don't accept formatting-only pull requests in the first place. Everything being formatted as a header is a consequence of github changing their markup syntax from time to time. It didn't start out that way. But it's still quite readable.

I'm not going to delete/archive this unmaintained repo because I don't remove open-source code once I release it. Anyone should be free to use the code in other projects or fork the repository if they so choose. They can't do that if I remove it.

**Comment by matkoniecz** [comment]
https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories may be useful for marking repos in such state

that clearly marks them as inactive, does not remove it and marks it as a read only

**Comment by dougmassay** [comment]
Please find another hobby. I'm not interested in your ideas.

**Pull request closed without merging**
